#include "dnsmasq_gen.hpp"
#include "keenetic_dns.hpp"
#include "../crypto/md5.hpp"
#include "../log/logger.hpp"

#include <chrono>
#include <functional>
#include <set>

namespace keen_pbr3 {

namespace {

static constexpr const char* kDnsProbeZone = "check.keen.pbr";
static constexpr size_t kBatchSize = 50;
static constexpr size_t kMaxDnsmasqRowLength = 1024;
static constexpr size_t kMaxDomainNameLength = 255;
static constexpr size_t kIpsetPrefixLen = sizeof("ipset=") - 1;
static constexpr size_t kNftsetPrefixLen = sizeof("nftset=") - 1;
static constexpr size_t kRebindPrefixLen = sizeof("rebind-domain-ok=") - 1;
static constexpr size_t kServerPrefixLen = sizeof("server=") - 1;
static constexpr const char* kNftSetPrefix = "/4#inet#KeenPbrTable#";
static constexpr const char* kNftSetMiddle = ",6#inet#KeenPbrTable#";
static constexpr size_t kNftSetPrefixLen = sizeof("/4#inet#KeenPbrTable#") - 1;
static constexpr size_t kNftSetMiddleLen = sizeof(",6#inet#KeenPbrTable#") - 1;

bool dns_config_uses_keenetic_server(const DnsConfig& dns_config) {
    for (const auto& server : dns_config.servers.value_or(std::vector<DnsServer>{})) {
        if (server.type.value_or(api::DnsServerType::STATIC) == api::DnsServerType::KEENETIC) {
            return true;
        }
    }
    return false;
}

std::string keenetic_static_domain_pattern(const std::string& domain) {
    if (domain.size() > 2 && domain[0] == '*' && domain[1] == '.') {
        return "/" + domain.substr(2);
    }
    return "/" + domain;
}

} // anonymous namespace

DnsmasqGenerator::DnsmasqGenerator(const DnsServerRegistry& dns_registry,
                                   ListStreamer& list_streamer,
                                   const RouteConfig& route_config,
                                   const DnsConfig& dns_config,
                                   const std::map<std::string, ListConfig>& lists,
                                   ResolverType resolver_type,
                                   std::string hash_version,
                                   bool ipv6_enabled)
    : dns_registry_(dns_registry),
      list_streamer_(list_streamer),
      route_config_(route_config),
      dns_config_(dns_config),
      lists_(lists),
      keenetic_static_entries_(dns_config_uses_keenetic_server(dns_config)
                                   ? get_keenetic_static_dns_entries()
                                   : std::vector<KeeneticStaticDnsEntry>{}),
      keenetic_dns_upstreams_(dns_config_uses_keenetic_server(dns_config)
                                  ? get_keenetic_dns_upstreams()
                                  : std::vector<KeeneticDnsUpstreamEntry>{}),
      resolver_type_(resolver_type),
      hash_version_(std::move(hash_version)),
      ipv6_enabled_(ipv6_enabled) {}

std::string DnsmasqGenerator::compute_config_hash() {
    crypto::detail::MD5State md5;
    generate_directives(
        nullptr,
        [&md5](const std::string& line) {
            md5.update(reinterpret_cast<const uint8_t*>(line.data()), line.size());
            static constexpr char newline = '\n';
            md5.update(reinterpret_cast<const uint8_t*>(&newline), 1);
        });
    return crypto::digest_to_hex(md5.digest());
}

std::string DnsmasqGenerator::compute_config_hash(
    const DnsServerRegistry& dns_registry,
    ListStreamer& list_streamer,
    const RouteConfig& route_config,
    const DnsConfig& dns_config,
    const std::map<std::string, ListConfig>& lists,
    std::string hash_version,
    bool ipv6_enabled)
{
    return DnsmasqGenerator(dns_registry, list_streamer, route_config,
                            dns_config, lists, ResolverType::DNSMASQ_IPSET,
                            std::move(hash_version), ipv6_enabled)
           .compute_config_hash();
}

void DnsmasqGenerator::generate_directives(
    std::ostream* out,
    const std::function<void(const std::string&)>& hash_record_callback) {
    if (hash_record_callback) {
        hash_record_callback("version|" + hash_version_);
        hash_record_callback(std::string("ipv6-enabled|") + (ipv6_enabled_ ? "1" : "0"));
    }

    if (out != nullptr) {
        const char* resolver_name = (resolver_type_ == ResolverType::DNSMASQ_IPSET)
            ? "dnsmasq-ipset" : "dnsmasq-nftset";
        *out << "# Generated by keen-pbr (" << resolver_name << ") - do not edit manually\n\n";
        *out << "address=/use-application-dns.net/\n\n";
    }

    if (dns_config_.dns_test_server.has_value()) {
        const auto parsed = parse_dns_address_str(dns_config_.dns_test_server->listen);
        if (hash_record_callback) {
            hash_record_callback(
                "probe-server|" + parsed.ip + "|" + std::to_string(parsed.port));
        }
        if (out != nullptr) {
            *out << "rebind-domain-ok=keen.pbr\n";
            *out << "server=/" << kDnsProbeZone << "/" << parsed.ip << "#" << parsed.port << "\n\n";
        }
    }

    if (!keenetic_static_entries_.empty()) {
        std::set<std::string> emitted_static_entries;
        bool wrote_header = false;
        for (const auto& entry : keenetic_static_entries_) {
            const std::string domain_pattern = keenetic_static_domain_pattern(entry.domain);
            const std::string dedupe_key = domain_pattern + "|" + entry.address;
            if (!emitted_static_entries.insert(dedupe_key).second) {
                continue;
            }
            if (hash_record_callback) {
                hash_record_callback("keenetic-static|" + domain_pattern + "|" + entry.address);
            }
            if (out != nullptr) {
                if (!wrote_header) {
                    *out << "# Keenetic static DNS entries\n";
                    wrote_header = true;
                }
                *out << "address=" << domain_pattern << "/" << entry.address << "\n";
            }
        }
        if (out != nullptr && wrote_header) {
            *out << "\n";
        }
    }

    if (out != nullptr && !keenetic_dns_upstreams_.empty()) {
        *out << "# Keenetic DNS is used:\n";
        for (const auto& upstream : keenetic_dns_upstreams_) {
            *out << "# " << upstream.address << " -> " << upstream.kind;
            if (!upstream.target.empty()) {
                *out << " | " << upstream.target;
            }
            *out << "\n";
        }
        *out << "\n";
    }

    size_t fallback_index = 0;
    for (const DnsServerConfig* server : dns_registry_.fallback_servers()) {
        if (hash_record_callback) {
            hash_record_callback(
                "fallback-server|" + std::to_string(fallback_index) +
                "|" + server->resolved_ip +
                "|" + std::to_string(server->port));
        }
        ++fallback_index;
        if (out != nullptr) {
            *out << "server=" << server->resolved_ip;
            if (server->port != 53) {
                *out << "#" << server->port;
            }
            *out << "\n";
        }
    }
    if (out != nullptr && dns_config_.fallback.has_value() && !dns_config_.fallback->empty()) {
        *out << "\n";
    }

    std::set<std::string> ipset_lists;
    for (const auto& rule : route_config_.rules.value_or(std::vector<RouteRule>{})) {
        if (!route_rule_enabled(rule)) {
            continue;
        }
        for (const auto& list_name : route_rule_lists(rule)) {
            ipset_lists.insert(list_name);
        }
    }

    std::map<std::string, std::string> dns_list_servers;
    std::map<std::string, bool> dns_list_allow_rebind;
    for (const auto& rule : dns_config_.rules.value_or(std::vector<DnsRule>{})) {
        if (!dns_rule_enabled(rule)) {
            continue;
        }
        for (const auto& list_name : rule.list) {
            if (dns_list_servers.find(list_name) == dns_list_servers.end()) {
                dns_list_servers[list_name] = rule.server;
                dns_list_allow_rebind[list_name] =
                    rule.allow_domain_rebinding.value_or(false);
            }
        }
    }

    std::set<std::string> all_lists;
    all_lists.insert(ipset_lists.begin(), ipset_lists.end());
    for (const auto& [list_name, _] : dns_list_servers) {
        all_lists.insert(list_name);
    }

    for (const auto& list_name : all_lists) {
        auto list_cfg_it = lists_.find(list_name);
        if (list_cfg_it == lists_.end()) {
            continue;
        }

        const bool needs_ipset = ipset_lists.count(list_name) > 0;

        std::vector<const DnsServerConfig*> dns_servers;
        auto dns_it = dns_list_servers.find(list_name);
        if (dns_it != dns_list_servers.end()) {
            dns_servers = dns_registry_.get_servers(dns_it->second);
        }

        const bool allow_domain_rebinding =
            dns_list_allow_rebind.find(list_name) != dns_list_allow_rebind.end()
            && dns_list_allow_rebind[list_name];

        bool wrote_list_header = false;
        auto ensure_list_header = [&]() {
            if (out != nullptr && !wrote_list_header) {
                *out << "# List: " << list_name << "\n";
                wrote_list_header = true;
            }
        };

        struct BatchState {
            bool enabled{false};
            std::string directive_name;
            size_t prefix_len{0};
            size_t suffix_len{0};
            size_t count{0};
            std::string domain_path;
            std::function<void(std::ostream&, const std::string&)> emit_line;
        };

        auto flush_batch = [&](BatchState& batch) {
            if (out == nullptr || !batch.enabled || batch.count == 0) {
                return;
            }
            batch.emit_line(*out, batch.domain_path);
            batch.domain_path.clear();
            batch.count = 0;
        };

        auto push_batch = [&](BatchState& batch, std::string_view domain) {
            if (out == nullptr || !batch.enabled) {
                return;
            }

            std::string next_chunk = batch.domain_path;
            next_chunk += "/";
            next_chunk += domain;
            if (batch.count >= kBatchSize ||
                batch.prefix_len + next_chunk.size() + batch.suffix_len > kMaxDnsmasqRowLength) {
                flush_batch(batch);
                next_chunk.assign("/");
                next_chunk += domain;
                if (batch.prefix_len + next_chunk.size() + batch.suffix_len >
                    kMaxDnsmasqRowLength) {
                    Logger::instance().warn(
                        "Skipping domain '{}' from list '{}': {} directive would exceed {} chars",
                        domain, list_name, batch.directive_name, kMaxDnsmasqRowLength);
                    return;
                }
            }

            batch.domain_path = std::move(next_chunk);
            ++batch.count;
        };

        BatchState ipset_batch;
        if (out != nullptr && needs_ipset) {
            const std::string set4 = ipset_name_v4(list_name);
            const std::string set6 = ipset_name_v6(list_name);
            if (resolver_type_ == ResolverType::DNSMASQ_IPSET) {
                ipset_batch.enabled = true;
                ipset_batch.directive_name = "ipset";
                ipset_batch.prefix_len = kIpsetPrefixLen;
                ipset_batch.suffix_len = ipv6_enabled_
                    ? 1 + set4.size() + 1 + set6.size()
                    : 1 + set4.size();
                ipset_batch.emit_line =
                    [set4, set6, ipv6_enabled = ipv6_enabled_](std::ostream& stream, const std::string& domain_path) {
                        stream << "ipset=" << domain_path << "/" << set4;
                        if (ipv6_enabled) {
                            stream << "," << set6;
                        }
                        stream << "\n";
                    };
            } else {
                ipset_batch.enabled = true;
                ipset_batch.directive_name = "nftset";
                ipset_batch.prefix_len = kNftsetPrefixLen;
                ipset_batch.suffix_len = ipv6_enabled_
                    ? kNftSetPrefixLen + set4.size() + kNftSetMiddleLen + set6.size()
                    : kNftSetPrefixLen + set4.size();
                ipset_batch.emit_line =
                    [set4, set6, ipv6_enabled = ipv6_enabled_](std::ostream& stream, const std::string& domain_path) {
                        stream << "nftset=" << domain_path
                               << kNftSetPrefix << set4;
                        if (ipv6_enabled) {
                            stream << kNftSetMiddle << set6;
                        }
                        stream << "\n";
                    };
            }
        }

        BatchState rebind_batch;
        if (out != nullptr && allow_domain_rebinding) {
            rebind_batch.enabled = true;
            rebind_batch.directive_name = "rebind-domain-ok";
            rebind_batch.prefix_len = kRebindPrefixLen;
            rebind_batch.suffix_len = 1;
            rebind_batch.emit_line = [](std::ostream& stream, const std::string& domain_path) {
                stream << "rebind-domain-ok=" << domain_path << "/\n";
            };
        }

        std::vector<BatchState> server_batches;
        server_batches.reserve(dns_servers.size());
        for (const DnsServerConfig* server : dns_servers) {
            std::string server_addr = server->resolved_ip;
            if (server->port != 53) {
                server_addr += "#" + std::to_string(server->port);
            }
            BatchState server_batch;
            if (out != nullptr) {
                server_batch.enabled = true;
                server_batch.directive_name = "server";
                server_batch.prefix_len = kServerPrefixLen;
                server_batch.suffix_len = 1 + server_addr.size();
                server_batch.emit_line =
                    [server_addr](std::ostream& stream, const std::string& domain_path) {
                        stream << "server=" << domain_path << "/" << server_addr << "\n";
                    };
            }
            server_batches.push_back(std::move(server_batch));
        }

        FunctionalVisitor collector([&](EntryType type, std::string_view entry) {
            if (type != EntryType::Domain) {
                return;
            }

            std::string bare = strip_wildcard(std::string(entry));
            if (bare.empty()) {
                return;
            }
            if (bare.size() > kMaxDomainNameLength) {
                Logger::instance().warn(
                    "Skipping invalid domain '{}' from list '{}': length {} exceeds {}",
                    bare, list_name, bare.size(), kMaxDomainNameLength);
                return;
            }

            if (needs_ipset) {
                if (hash_record_callback) {
                    hash_record_callback("domain-route|" + list_name + "|" + bare);
                }
            }
            if (allow_domain_rebinding) {
                if (hash_record_callback) {
                    hash_record_callback("domain-rebind|" + list_name + "|" + bare);
                }
            }
            for (size_t server_index = 0; server_index < dns_servers.size(); ++server_index) {
                const DnsServerConfig* server = dns_servers[server_index];
                if (hash_record_callback) {
                    hash_record_callback(
                        "domain-server|" + list_name + "|" + bare + "|" +
                        std::to_string(server_index) + "|" + server->resolved_ip + "|" +
                        std::to_string(server->port));
                }
            }
            if (!needs_ipset && !allow_domain_rebinding && dns_servers.empty()) {
                return;
            }

            ensure_list_header();
            push_batch(ipset_batch, bare);
            push_batch(rebind_batch, bare);
            for (auto& server_batch : server_batches) {
                push_batch(server_batch, bare);
            }
        });
        list_streamer_.stream_list_preferring_cache(list_name, list_cfg_it->second, collector);

        flush_batch(ipset_batch);
        flush_batch(rebind_batch);
        for (auto& server_batch : server_batches) {
            flush_batch(server_batch);
        }
        if (out != nullptr && wrote_list_header) {
            *out << "\n";
        }
    }
}

void DnsmasqGenerator::generate(std::ostream& out) {
    crypto::detail::MD5State md5;
    generate_directives(
        &out,
        [&md5](const std::string& line) {
            md5.update(reinterpret_cast<const uint8_t*>(line.data()), line.size());
            static constexpr char newline = '\n';
            md5.update(reinterpret_cast<const uint8_t*>(&newline), 1);
        });
    const std::string hash = crypto::digest_to_hex(md5.digest());
    const auto now_ts = std::chrono::duration_cast<std::chrono::seconds>(
        std::chrono::system_clock::now().time_since_epoch()).count();
    out << "txt-record=config-hash.keen.pbr," << now_ts << "|" << hash << "\n";
}

ResolverType DnsmasqGenerator::parse_resolver_type(const std::string& s) {
    if (s == "dnsmasq-ipset")  return ResolverType::DNSMASQ_IPSET;
    if (s == "dnsmasq-nftset") return ResolverType::DNSMASQ_NFTSET;
    throw std::invalid_argument("Unknown resolver type: " + s);
}

std::string DnsmasqGenerator::strip_wildcard(const std::string& domain) {
    if (domain.size() > 2 && domain[0] == '*' && domain[1] == '.') {
        return domain.substr(2);
    }
    return domain;
}

} // namespace keen_pbr3
